name: Contemporary Cruise Crew
favicon: null
layout_spectrum: 0.5688564830925316
typography_spectrum: 0.5816979731898755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.48150852625258267
  lightness: 0.7276823939755559
  saturation: 0.9649602440185845
  rhythmicContrast: 0.7445064522325993
purpose: []
