name: Contemporary Cruise Crew
favicon: null
layout_spectrum: 0.02451
typography_spectrum: 0.91301
title: CCC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1e11'
    - '#bcddc2'
    - '#27692c'
    - '#9c9489'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
