name: Contemporary Cruise Crew
favicon: null
layout_spectrum: 0.20626
typography_spectrum: 0.18597
title: CCC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aca9a2'
    - '#0b150c'
    - '#383c47'
    - '#68804f'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
